const data = [
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'Bauuuu',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Mamat',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "",
        text3: '' ,
        text4: '',
        text5: '',
        text6: '',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Kak Lisda',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Adan',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Yunus',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Fikrul',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Asade',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Nisa',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Tullah',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Wani',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Noe',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Ulfa',
        text10: 'ehehe',
    },
]

export default data
