const data = [
    {
        img: 'https://image.ibb.co/fYzTrb/lastofus.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Sarah',
        text10: 'ehehe',
    },
    {
        img: 'https://image.ibb.co/fYzTrb/lastofus.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Sarah',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/X7CzRqQ/Desain-tanpa-judul-2.png',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo' ,
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Sarah',
        text10: 'ehehe',
    },
]

export default data