const data = [
    {
        title: 'Dari Mamat',
        text: 'Untuk Afni,',
        text1: "Usia baru nih,",
        text2: "tapi pasangan tidak boleh baru nh.",
        text3: 'jangan sering tanya soal nikah dlu',
        text4: 'karna masih lama, bisa sih nikah sekarang',
        text5: 'tapi masa km mau uang panai cuman 5jt',
        text6: 'wkwk canda ji ndut',
        text7: 'btw hbd ya, semoga semua dipanjangkn',
        text8: 'Happy Birthday,',
        text9: '♥Mamat',
    },
    {
        title: 'Dari Kak Lisda',
        text: 'Untuk afni,',
        text1: "Happy Birthday orang baik",
        text2: "semoga bahagia terus yaaa.....",
        text3: '',
        text4: '',
        text5: '',
        text6: '',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Lisda',
    },
    {
        title: 'Dari Adan',
        text: 'Untuk Afni,',
        text1: "hbd,",
        text2: "untuk doanya, doa sendirimi nah,",
        text3: 'jangan manja, besar mako',
        text4: '',
        text5: '',
        text6: '',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Adan',
    },
    {
        title: 'Dari Yunus',
        text: 'Untuk Afni,',
        text1: "HBD Afni,",
        text2: "Panjang Umur dan sehat selalu",
        text3: 'semoga makin subuur',
        text4: '',
        text5: '',
        text6: '',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Yunus',
    },
    {
        title: 'Dari Fikrul',
        text: 'Untuk Afni,',
        text1: "HBD Afni,",
        text2: "panjang umur, sehat selalu. ",
        text3: 'kuharap ulang tahunmu semanis kuenya.',
        text4: 'dan tahun berikutnya dipenuhi sukacita',
        text5: 'bersama teman-teman.',
        text6: 'ingat jangan bertingkah sesuai usia',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Fikrul',
    },
    {
        title: 'Dari Asad',
        text: 'Untuk Afni,',
        text1: "Hepibesdey bucin,",
        text2: "sehat selalu, di lancarkan rejekinya,",
        text3: 'kurangilah perbucinan.',
        text4: 'Ingat ko 21 mi umurmu,',
        text5: ' intinya dewasa mko lah, ',
        text6: 'ngerti mko toh kalau dewasa orang,',
        text7: 'traktirannya lah',
        text8: 'Happy Birthday,',
        text9: '♥Asad',
    },
    {
        title: 'Dari Tullah',
        text: 'Untuk Afni,',
        text1: "Assalamualaikum",
        text2: "Bismillahirrahmanirrahim",
        text3: 'Barakallahu fi umrik afni',
        text4: 'Semoga cepat jadi sultan',
        text5: '',
        text6: '',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Tullah',
    },
    {
        title: 'Dari Shobur',
        text: 'Untuk Afni,',
        text1: "Hbd apni,",
        text2: "semoga panjang umur sehat selalu,",
        text3: 'dilancarkan rejekinya,',
        text4: 'cepat"mi nikah sama mamat ',
        text5: 'biar bisaka makan gratis',
        text6: 'dan kurang"i koro"an nya :v',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Shobur',
    },
    {
        title: 'Dari Jeniar',
        text: 'Untuk Afni',
        text1: "HBD EA AFNI ",
        text2: "SEMOGA PANJANG UMUR,",
        text3: 'ADAKAH YOTTA BOSQUE',
        text4: '',
        text5: '',
        text6: '',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Jeniar',
    },
    {
        title: 'Dari Alfian',
        text: 'Untuk Afni,',
        text1: "Miladuka sahida, Afni,",
        text2: "Barakallahu fi umrik,",
        text3: 'semoga menjadi lebih dewasa',
        text4: 'kuat menghadapi tantangan dan rintangan,',
        text5: 'be strong women,',
        text6: 'Dan semoga semua harapan jadi nyata,',
        text8: 'Happy Birthday,',
        text9: '♥Alfian',
    },
    {
        title: 'Dari Hadak',
        text: 'Dear Afni,',
        text1: "Semoga dengan bertambahnya usiamu,",
        text2: "semakin sempurna juga iman ",
        text3: 'serta akhlakmu',
        text4: 'Tiada kado yang paling istimewa selain doa',
        text5: 'semoga engkau selalu bahagia, dan',
        text6: 'diberkahi dan dilindungi oleh Allah SWT',
        text7: '',
        text8: 'Happy Birthday,',
        text9: '♥Hadak',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo',
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Noe',
        text10: 'ehehe',
    },
    {
        img: 'https://i.ibb.co/jyrts86/21.jpg',
        title: 'You are not a Fossil! (YET)',
        text: 'Dear Dad,',
        text1: "Let's see...",
        text2: "You’re never around, you",
        text3: 'hate the music I’m into, yo',
        text4: 'practically despise the movies I',
        text5: 'like, and yet somehow you still',
        text6: 'manage to be the best dad every year.',
        text7: 'How do you do that? :)',
        text8: 'Happy Birthday, papa!',
        text9: '♥Ulfa',
        text10: 'ehehe',
    },
]

export default data
